language: node_js
node_js:
- '0.12'
before_script:
- npm install
script:
- npm test
after_script:
- npm run coveralls
env:
  global:
    secure: gxj3OkY6GcAklqM9gHvxoKeMDM8Gm7MQK3JLBXzQq6BV40tlxlQcJWbYl/rbjf9jIUXKlSM26C7ii3x1wEGqP9cQneaPeVvs84hQYHS1rLCl9BsZEFgSYnHldvbImGLHx/VTYWmLVC1WFVkCvZPbVda9RPAilI7qr2nSAOH/FINRMfaspHOa44ygsj+hnanTWLXyFlPkGAIAHcQ/UB+dOL/d2SW8Fk0VS10HiRfAlSY/xGC/SXQZmO6s6dG5k4kuYStS4ahhcWNQktOX5sYpBGrfOapCPrU3LAvde8XCX68wLPu2t+oT2iVNjD+2U0Ta9nRsTV+xyOmoM78AdMO2Y4OHbeFwaHQdarl0oqNorJUCcVDls5BtTfa8QPSfcO253/whAkVVuCVVCJhrxBQtqlqFeaEEnFDgrmy1GvEUoXJYeeEMYw99wvJMSXISQQOyzF8bJokP4fLReLZQOwVplT0O5hrRdWYehO2hT9Hnk+fSxgR5Recu+ShjPTy5NA78EmlrTThKrvEpPh6TvWPFY/1Mk2ROT71gN9JX5eliOcClEZu1hwzyhmPMaY+9iPxxKyQ14s4zXELOfUvTpuCKPw2UozX/U5QP7jWuefVR8BolZscbuhnu97rb3yNbZsP0tYyU3zo0dFJUSWvMfdglBXXu8ASgG5jY2NHSOpRc4hI=
notifications:
  hipchat:
    rooms:
      secure: j7VxKS8eB+uP9kXXGRlemid6stTDNkBkmPD0DfG3zw01tyAGyII97gnioFUJPbw+3sZH4gmPukViRhmrCTvjTj99ibKAO33KVl9pRTPZI4GuncbFq5t/KbSLaGm3EBAJCBGEuMIS3ki0AzBsCT5P+2IY455+bwl1CSt1AsBaloD9hnZ6+bpCOgdcCPt1LoFFdPnN8Jhul/emOJ+RU82/PBgWPd3vm7h7oF6yazltcBjKFZvXJw24q7acVLON1wDw0i56p2JIrDAD2u29ueyqHNTwCT4b/UJxqTTjsNnMiC3CfhdLNpwLMyQT5tFthFaGq67UkSxgvlA1fZf4M+GQ1S/vOoO6+FGW0WZ/uDfI3YHktfRM/uZELHU6DftGQ1Yz7djI6bjEKMoSPwXyND1oHQTPZOYCKDXoXGq13vPe+coIiiPLINCpT/mAN0R2Nf+4bdQy5alqkAYHBH1SriRErFEelNEa1H2Y5KL17hLQdLD2RUlXBV7mlkPxZqaTDyH3jwXmFlvQCnQyx8cHc22ZF5YqXbsXH5SYw1JU3ymJrWcQwyfZ5FC7T+pU4thIll6/m2C43K0nW221DPuloVSeQZPeHGKvmuMQUwcD6F04FA1xGgHz6ikQmc46H53aHx5CeMg7/3Lj+ev9BE9LCoJw9pavtZ6hTYzlFGon8t5bzAA=
